### ISSUE TITLE
Make contact form do stuff

### ISSUE THREAD

**Issue by clemmy** [ZooHouse/zh-landing#43]
First question is how we want to do it...? Make our own backend (e.g. Heroku with SendGrid), or use a SaaS?

http://www.wufoo.com/
https://formspree.io/
https://formkeep.com/
https://getsimpleform.com/
https://www.formingo.co/

**Comment by raywan** [comment]
Let's not waste our time building our own. We should use an existing service.
@ntimpham @clemmy I'll take this one

**Comment by raywan** [comment]
Resolved in #45
